---

- name: Get Public VPC Info
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_guid_public_zone_name }}"
      "tag-key": ['guid', 'owner', 'email']
  register: vpc_info


- name: Get Subnet information
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag-key": ['guid', 'owner', 'email']
  register: subnet_info

- name: Set facts for VPC and Subnet info
  set_fact:
    aws_vpc_id: "{{ vpc_info.vpcs[0].id }}"
    aws_subnet_id: "{{ subnet_info.subnets[0].id }}"
    rhoe_email_owner: "{{ vpc_info.vpcs[0].tags.email }}"
    rhoe_guid: "{{ vpc_info.vpcs[0].tags.guid }}"