---
# tasks file for scope-rhoe-aws
- name: Set up Route53 Information
  ansible.builtin.include_tasks: get_route53_info.yaml

- name: Set up VPC Information
  ansible.builtin.include_tasks: get_vpc_info.yaml
