---
- name: Destroy Grain Tower Workloads
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    action: destroy # deploy or destroy

  tasks:

    - name: Scope RHOE AWS Environment
      ansible.builtin.include_role:
        name: "scope-rhoe-aws"

# ============================================================
# Per-Workload Infrastructure Destruction
# ============================================================

    - name: Destroy RHOE AWS Infrastructure for different workloads
      block:

        - name: RHOE - EC2 - IDM | AWS Infrastructure
          when: (deploy_rh_idm is defined) and deploy_rh_idm | bool
          ansible.builtin.include_role:
            name: "rhoe-ec2-idm"

        - name: RHOE - EC2 - Bastion | AWS Infrastructure
          when: (deploy_bastion is defined) and deploy_bastion | bool
          ansible.builtin.include_role:
            name: "rhoe-ec2-bastion"
