---
# Workload selection - default is false
deploy_bastion: true
deploy_rh_idm: true
deploy_gitlab: true
#deploy_keystone: true
deploy_ocp4: true
deploy_ocp4_workload_machinelearning_workshop: true

# Public Key definitions
shared_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
# Defined once with a shared key
bastion_ec2_keypair: "{{ shared_public_key }}"
gitlab_ec2_keypair: "{{ shared_public_key }}"
idm_ec2_keypair: "{{ shared_public_key }}"
keystone_ec2_keypair: "{{ shared_public_key }}"

############################################################
# The variable below are only used for OpenShift cluster deployments
# OpenShift Pull Secret
ocp_pull_secret: "{{ lookup('file', '~/rh-ocp-pull-secret.json') }}"
ocp_ssh_public_key: "{{ shared_public_key }}"

# AWS Secrets
target_aws_access_key: "{{ lookup('ansible.builtin.ini', 'aws_access_key_id', section='default', file='~/.aws/credentials') }}"
target_aws_access_secret: "{{ lookup('ansible.builtin.ini', 'aws_secret_access_key', section='default', file='~/.aws/credentials') }}"