---
# tasks file for rhoe-ec2-gitlab

- name: Deploy the Gitlab Environment
  when: action == "deploy"
  block:
    - name: Create the AWS Infrastructure
      when: stage == "aws_infra"
      ansible.builtin.include_tasks: aws_infra_deploy.yaml

    - name: Configure the Gitlab instance
      when: stage == "configure"
      ansible.builtin.include_tasks: configure.yaml

- name: Destroy the Gitlab Environment
  when: action == "destroy"
  ansible.builtin.include_tasks: destroy.yaml
