---

- name: Wait for SSH to come up
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 360

- name: Update system packages
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true
  register: update_task_result

- name: Install base packages
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    state: present
    name: ['nano', 'firewalld', 'python3-libselinux', '@idm:DL1']

- name: Install IDM server packages
  ansible.builtin.yum:
    name: "{{ idm_server_pkgs }}"
    state: present
  delay: 10
  register: result
  retries: 3
  until: result is succeeded

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Reboot immediately if there were new packages installed
  ansible.builtin.shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: update_task_result is changed

- name: Wait for the reboot to complete if there were new packages installed
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: update_task_result is changed
  delay: 10
  register: wait_result
  retries: 3
  until: wait_result is succeeded

- name: Collect facts
  ansible.builtin.setup:

- name: Connect to new instance and set hostname
  ansible.builtin.hostname:
    name: "{{ idm_hostname }}.{{ aws_guid_public_zone_name }}"

- name: Set /etc/hosts file
  ansible.builtin.copy:
    dest: "/etc/hosts"
    content: |
      127.0.0.1 localhost localdomain
      {{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }} {{ idm_hostname }}.{{ aws_guid_public_zone_name }} {{ aws_guid_public_zone_name }}

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Connect to RH IDM server and set firewall
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    service: "{{ item }}"
  with_items:
    - freeipa-ldap
    - freeipa-ldaps
    - dns
    - ntp
    - ssh
    - https
    - http

- name: Connect to RH IDM server and set firewall for port 8080
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    port: 8080/tcp

- name: Echo the IDM server installer
  ansible.builtin.debug:
    msg: "{{ idm_server_install_base_command }} {{ idm_server_install_options | join(' ') }}"

- name: Check to see if IDM is already configured
  ansible.builtin.stat:
    path: /etc/ipa/default.conf
  register: pathToIPAConfig

- name: Run the IDM server installer
  ansible.builtin.command: "{{ idm_server_install_base_command }} {{ idm_server_install_options | join(' ') }}"
  args:
    creates: /etc/ipa/default.conf

- name: Do initial kinit admin auth
  when: not pathToIPAConfig.stat.exists
  ansible.builtin.shell: "echo '{{ idm_server_admin_password }}' | kinit admin"

- name: Create groups
  when: idm_provision_groups and not pathToIPAConfig.stat.exists
  ansible.builtin.shell: "ipa group-add {{ group_item }}"
  loop: "{{ idm_provision_groups_groups }}"
  loop_control:
    loop_var: group_item

- name: Create batch student users
  when: idm_provision_users and not pathToIPAConfig.stat.exists
  ansible.builtin.shell: "echo '{{ idm_provision_users_password }}' | ipa user-add {{ idm_provision_users_prefix }}{{ item }}{{ idm_provision_users_suffix }} --first=Student --last=User{{ item }} --password --shell=/bin/bash"
  with_sequence: start={{ idm_provision_users_start }} count={{ idm_provision_users_count }}

- name: Set expiration out for a decade so users dont have to reset passwords
  when: idm_provision_users and not pathToIPAConfig.stat.exists
  ansible.builtin.shell: "ipa user-mod {{ idm_provision_users_prefix }}{{ item }}{{ idm_provision_users_suffix }} --setattr krbPasswordExpiration=20360420162000Z"
  with_sequence: start={{ idm_provision_users_start }} count={{ idm_provision_users_count }}

- name: Add users to group
  when: idm_provision_users and not pathToIPAConfig.stat.exists
  ansible.builtin.shell: "ipa group-add-member {{ idm_provision_users_group }} --users={{ idm_provision_users_prefix }}{{ item }}{{ idm_provision_users_suffix }}"
  with_sequence: start={{ idm_provision_users_start }} count={{ idm_provision_users_count }}

- name: Check to see if IDM is already configured
  ansible.builtin.stat:
    path: /etc/ipa/idm-binddn.update
  register: pathToIPABindDN

- name: Copy Binding User template file over
  when: not pathToIPAConfig.stat.exists
  template:
    src: templates/idm-binddn.update.j2
    dest: /etc/ipa/idm-binddn.update

- name: Create Binding user from template
  when: not pathToIPABindDN.stat.exists
  ansible.builtin.shell: "ipa-ldap-updater /etc/ipa/idm-binddn.update"

- name: Restart ipa services
  when: not pathToIPAConfig.stat.exists
  ansible.builtin.service:
    enabled: true
    name: ipa
    state: restarted
