---
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 360

- name: Connect to new instance and set hostname
  hostname:
    name: "{{ idm_hostname }}.{{ aws_guid_public_zone_name }}"

- name: Set /etc/hosts file
  copy:
    dest: "/etc/hosts"
    content: |
      127.0.0.1 localhost localdomain
      {{ inventory_hostname }} {{ idm_hostname }}.{{ aws_guid_public_zone_name }} {{ aws_guid_public_zone_name }}

- name: Update base packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
  register: update_task_result
      
- name: Reboot immediately if there were new packages installed
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: update_task_result is changed

- name: Wait for the reboot to complete if there were new packages installed
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: update_task_result is changed
  delay: 10
  register: wait_result
  retries: 3
  until: wait_result is succeeded

- name: Connect to instance and install base packages
  become: yes
  yum:
    disable_gpg_check: yes
    state: present
    name: ['nano', 'firewalld', 'python3-libselinux', '@idm:DL1']

- name: Disable SELinux
  selinux:
    state: disabled

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Connect to RH IDM server and set firewall
  ansible.posix.firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    service: "{{ item }}"
  with_items:
    - freeipa-ldap
    - freeipa-ldaps
    - dns
    - ntp
    - ssh
    - https
    - http

- name: Connect to RH IDM server and set firewall for port 8080
  ansible.posix.firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: 8080/tcp

- name: Install FreeIPA server packages
  yum:
    name: "{{ freeipa_server_pkgs }}"
    state: present
  delay: 10
  register: result
  retries: 3
  until: result is succeeded