---

# ======================================================================== AWS INFRASTRUCTURE

- name: Create EC2 Key Pair from Public Key Input
  tags:
    - aws_infrastructure
    - aws_ec2_key
  amazon.aws.ec2_key:
    region: "{{ aws_region }}"
    name: "{{ bastion_keypair_name }}"
    key_material: "{{ bastion_ec2_keypair }}"

- name: Create Bastion Host Security Group
  tags:
    - aws_infrastructure
    - aws_ec2_group
  amazon.aws.ec2_group:
    name: bastion-sg
    description: A Security Group for Bastion hosts
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
      - proto: udp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
    tags:
      guid: "{{ rhoe_guid }}"
      owner: "{{ rhoe_email_owner }}"
      email: "{{ rhoe_email_owner }}"
      deployer: grain-tower
      deployment: bastion
  register: bastion_sg

- name: Find RHEL AMI
  tags:
    - aws_infrastructure
    - aws_ec2_ami_info
  amazon.aws.ec2_ami_info:
    region: "{{ aws_region }}"
    owners: 309956199498
    filters:
      name: "RHEL*8.4*x86_64*"
  register: rhel_ami

- name: See if the EC2 instance exists because these new modules suck
  tags:
    - aws_infrastructure
    - aws_ec2_instance_info
  amazon.aws.ec2_instance_info:
    filters:
      "tag:guid": "{{ rhoe_guid }}"
      "tag:owner": "{{ rhoe_email_owner }}"
      "tag:email": "{{ rhoe_email_owner }}"
      "tag:Name": "{{ bastion_hostname }}"
      "tag:base_domain": "{{ aws_guid_public_zone_name }}"
      "tag:deployer": grain-tower
      "tag:group": bastion-sg
      instance-state-name: ["running", "pending"]
    region: "{{ aws_region }}"
  register: ec2_instance_info

- name: Create EC2 Instance for Bastion Host Server
  when: ec2_instance_info.instances | length == 0
  tags:
    - aws_infrastructure
    - aws_ec2_instance
  amazon.aws.ec2_instance:
    network:
      assign_public_ip: true
    tags:
      Name: "{{ bastion_hostname }}"
      group: bastion-sg
      guid: "{{ rhoe_guid }}"
      owner: "{{ rhoe_email_owner }}"
      email: "{{ rhoe_email_owner }}"
      base_domain: "{{ aws_guid_public_zone_name }}"
      deployer: grain-tower
    region: "{{ aws_region }}"
    key_name: "{{ bastion_keypair_name }}"
    instance_type: "{{ bastion_ec2_instance_type }}"
    image_id: "{{ (rhel_ami.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last).image_id }}"
    wait: true
    vpc_subnet_id: "{{ aws_subnet_id }}"
    exact_count: 1
    security_group: "{{ bastion_sg.group_id }}"
  register: aws_ec2_instance

- name: Get the EC2 Instance and wait until it has a public ip attached
  tags:
    - always
  amazon.aws.ec2_instance_info:
    filters:
      "tag:guid": "{{ rhoe_guid }}"
      "tag:owner": "{{ rhoe_email_owner }}"
      "tag:email": "{{ rhoe_email_owner }}"
      "tag:Name": "{{ bastion_hostname }}"
      "tag:base_domain": "{{ aws_guid_public_zone_name }}"
      "tag:deployer": grain-tower
      "tag:group": bastion-sg
      instance-state-name: ["running", "pending"]
    region: "{{ aws_region }}"
  register: ec2_instance_info
  until: ec2_instance_info.instances[0].public_ip_address is defined
  retries: 30
  delay: 10

- name: Set fact for Route53 entries
  tags:
    - aws_infrastructure
    - aws_route53
  ansible.builtin.set_fact:
    r53_records:
      - name: "{{ bastion_hostname }}.{{ aws_guid_public_zone_name }}"
        type: A
        ttl: 300
        value: "{{ ec2_instance_info.instances[0].public_ip_address }}"
      - name: "*.{{ bastion_hostname }}.{{ aws_guid_public_zone_name }}"
        type: A
        ttl: 300
        value: "{{ ec2_instance_info.instances[0].public_ip_address }}"

- name: Create Route53 A Record Entries for Bastion Host
  tags:
    - aws_infrastructure
    - aws_route53
  community.aws.route53:
    state: present
    zone: "{{ aws_guid_public_zone_name }}"
    record: "{{ record_item.name }}"
    type: "{{ record_item.type }}"
    ttl: "{{ record_item.ttl }}"
    value: "{{ record_item.value }}"
    overwrite: true
  loop: "{{ r53_records }}"
  loop_control:
    loop_var: record_item
  when: (record_item.type == "A")

- name: Add the new Bastion Host to a new inventory
  tags:
    - always
  ansible.builtin.add_host:
    hostname: '{{ ec2_instance_info.instances[0].public_ip_address }}'
    groups:
      - bastion
    ansible_user: ec2-user
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: "/usr/libexec/platform-python"
    aws_guid_public_zone_name: "{{ aws_guid_public_zone_name }}"
    rhoe_email_owner: "{{ rhoe_email_owner }}"
