---
# tasks file for rhoe-ec2-idm

- name: Deploy the IDM Environment
  when: action == "deploy"
  block:
    - name: Create the AWS Infrastructure
      when: stage == "aws_infra"
      ansible.builtin.include_tasks: aws_infra_deploy.yaml

    - name: Configure the IDM instance
      when: stage == "configure"
      ansible.builtin.include_tasks: idm_config.yaml

- name: Destroy the IDM Environment
  when: action == "destroy"
  ansible.builtin.include_tasks: destroy.yaml
