---
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 360

- name: Update system packages
  yum:
    name: "*"
    state: latest
    update_cache: true
  register: update_task_result

- name: Install AIO OpenStack server packages
  yum:
    name: "{{ openstack_server_pkgs }}"
    state: present
  delay: 10
  register: result
  retries: 3
  until: result is succeeded

- name: Create new stack

- name: Set sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^stack ALL=(ALL) NOPASSWD: ALL'
    line: 'stack ALL=(ALL) NOPASSWD: ALL'
    validate: '^stack ALL=(ALL) NOPASSWD: ALL'

- name: Clone down devstack repo
  git:
    clone: true
    force: true
    repo: https://opendev.org/openstack/devstack
    dest: /root/devstack

- name: Setup local.conf


- name: Start devstack install

